import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { useStatsifyContext } from "../context/context";
import { fetchUserDetails } from "../utils";
import Loader from "../components/views/Loader";
import SignIn from "../components/views/SignIn";
import LandingPage from "../components/views/LandingPage";

export default function Home() {
  const { isLoggedIn, setIsLoggedIn, user, setUser, isLoading, setIsLoading } =
    useStatsifyContext();
  const router = useRouter();
  useEffect(() => {
    if (!isLoggedIn) {
      setIsLoading(false);
    }
    const fetchData = async () => {
      const res = await fetchUserDetails(router.query.code);
      if (res.status === 403) {
        router.push("/error");
      } else if (res.data) {
        setUser(res.data);
        setIsLoggedIn(true);
        setIsLoading(false);
      }
    };

    if (router.query.code && !user) {
      setIsLoading(true);
      try {
        fetchData();
        router.replace("/", undefined, { shallow: true });
      } catch (error) {
        console.error(error);
      }
    }
  }, [router, setUser, setIsLoggedIn, setIsLoading, user, isLoggedIn]);
  return (
    <>
      <Head>
        <title>Statsify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading && <Loader />}

      <main className="h-screen w-screen flex justify-center items-center bg-[#202121]">
        {!isLoggedIn && !isLoading && <SignIn />}
        {isLoggedIn && !isLoading && <LandingPage />}
      </main>
    </>
  );
}
